services:
  backend:
    build: ./backend
    image: alphaMail/backend:latest
    ports:
      - "8081:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - YOUR_ACCESS_KEY=${YOUR_ACCESS_KEY}
      - YOUR_SECRET_KEY=${YOUR_SECRET_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
  frontend:
    build: ./frontend/mail-app
    image: alphaMail/frontend:latest
    ports:
      - "3000:80" 