services:
  backend:
    build: ./backend
    image: alphaMail/backend:latest
    ports:
      - "8081:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - YOUR_ACCESS_KEY=${YOUR_ACCESS_KEY}
      - YOUR_SECRET_KEY=${YOUR_SECRET_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - CLAUDE_SECRET_KEY=${CLAUDE_SECRET_KEY}
      - CLAUDE_BASE_URL=${CLAUDE_BASE_URL}
    networks:
      - alphaMail-networks

  frontend:
    build: ./frontend/mail-app
    image: alphaMail/frontend:latest
    ports:
      - "3000:80" 
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_PUBLIC_SERVICE_KEY=${VITE_PUBLIC_SERVICE_KEY}
      - VITE_PUBLIC_HOLIDAY_API_URL=${VITE_PUBLIC_HOLIDAY_API_URL}
    networks:
      - alphaMail-networks

  rag:
    build: ./AI/server/rag
    image: alphaMail/rag:latest
    ports:
      - "5000:5000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}  
    volumes:
      - pip-cache:/root/.cache/pip
      - chroma-data:/app/db 
    networks:
      - alphaMail-networks
      
  ocr:
    build: ./AI/server/ocr
    image: alphaMail/ocr:latest
    ports:
      - "3001:3000"
    environment:
      - OCR_SECRET=${OCR_SECRET}
      - OCR_API_URL=${OCR_API_URL}
    networks:
      - alphaMail-networks

  mcp-server:
    build: ./AI/server/mcp-server
    image: alphaMail/mcp-server:latest
    ports:
      - "8000:8000"
    networks:
      - alphaMail-networks

  mcp-client:
    build: ./AI/server/mcp-client
    image: alphaMail/mcp-client:latest
    ports:
      - "8001:8001"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    networks : 
      - alphaMail-networks
      
  chatbot:
    build: ./AI/CHATBOT/services
    image: alphaMail/chatbot:latest
    ports:
      - "5001:5001"
    volumes:
      - chatbot-db:/app/db
    networks:
      - alphaMail-networks

volumes:
  pip-cache: {}
  chroma-data: {}
  chatbot-db: {}


networks:
  alphaMail-networks:
    driver: bridge