services:
  backend:
    build: ./backend
    image: alphaMail/backend:latest
    ports:
      - "8081:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - YOUR_ACCESS_KEY=${YOUR_ACCESS_KEY}
      - YOUR_SECRET_KEY=${YOUR_SECRET_KEY}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - CLAUDE_SECRET_KEY=${CLAUDE_SECRET_KEY}
      - CLAUDE_BASE_URL=${CLAUDE_BASE_URL}
  frontend:
    build: ./frontend/mail-app
    image: alphaMail/frontend:latest
    ports:
      - "3000:80" 
  rag:
    build: ./AI/server/RAG
    image: alphaMail/rag:latest
    ports:
      - "5000:5000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}  
    volumes:
      - pip-cache:/root/.cache/pip
  ocr:
    build: ./AI/server/ocr
    image: alphaMail/ocr:latest
    ports:
      - "3001:3000"
    environment:
      - OCR_SECRET=${OCR_SECRET}
      - OCR_API_URL=${OCR_API_URL}

  mcp-server:
    build: ./AI/server/mcp-server
    image: alphaMail/mcp-server:latest
    ports:
      - "8000:8000"

  mcp-client:
    build: ./AI/server/mcp-client
    image: alphaMail/mcp-client:latest
    ports:
      - "8001:8001"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
volumes:
  pip-cache: {}