services:
  backend:
    image: alphaMail/backend:latest
    ports:
      - "8081:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  frontend:
    image: alphaMail/frontend:latest
    ports:
      - "3000:3000"