// Mock 데이터 생성 팩토리

export const createMockSchedules = () => {
    const now = new Date();
    return {
      data: [
        {
          scheduleId: 1,
          name: '오전 팀 회의',
          startTime: new Date(now.getTime() + 1 * 60 * 60 * 1000).toISOString(),
          endTime: new Date(now.getTime() + 2 * 60 * 60 * 1000).toISOString(),
          description: '주간 팀 회의',
        },
        {
          scheduleId: 2,
          name: '프로젝트 논의',
          startTime: new Date(now.getTime() + 3 * 60 * 60 * 1000).toISOString(),
          endTime: new Date(now.getTime() + 4 * 60 * 60 * 1000).toISOString(),
          description: '신규 프로젝트 진행 상황 점검',
        },
        {
          scheduleId: 3,
          name: '클라이언트 미팅',
          startTime: new Date(now.getTime() + 5 * 60 * 60 * 1000).toISOString(),
          endTime: new Date(now.getTime() + 6 * 60 * 60 * 1000).toISOString(),
          description: '분기 리뷰 회의',
        },
      ],
    };
  };
  
  // Mock 메일 목록 응답 (MailListResponse 타입)
  export const createMockMailList = () => {
    const now = new Date();
    return {
      emails: [
        {
          id: 1,
          subject: '프로젝트 회의 일정 안내',
          sender: 'john.doe@company.com',
          recipients: ['admin@alphamail.my'],
          receivedDateTime: new Date(now.getTime() - 3600000).toISOString(),
          sentDateTime: new Date(now.getTime() - 3600000).toISOString(),
          readStatus: false,
          size: 2048,
        },
        {
          id: 2,
          subject: '[발주] 사무용품 구매 요청',
          sender: 'jane.smith@supplier.com',
          recipients: ['admin@alphamail.my'],
          receivedDateTime: new Date(now.getTime() - 7200000).toISOString(),
          sentDateTime: new Date(now.getTime() - 7200000).toISOString(),
          readStatus: false,
          size: 4096,
        },
        {
          id: 3,
          subject: '견적 요청에 대한 회신',
          sender: 'support@client.com',
          recipients: ['admin@alphamail.my'],
          receivedDateTime: new Date(now.getTime() - 10800000).toISOString(),
          sentDateTime: new Date(now.getTime() - 10800000).toISOString(),
          readStatus: false,
          size: 3072,
        },
        {
          id: 4,
          subject: '품질 개선 사항',
          sender: 'qa@company.com',
          recipients: ['admin@alphamail.my'],
          receivedDateTime: new Date(now.getTime() - 14400000).toISOString(),
          sentDateTime: new Date(now.getTime() - 14400000).toISOString(),
          readStatus: false,
          size: 2560,
        },
        {
          id: 5,
          subject: '고객 피드백 공유',
          sender: 'customer@client.com',
          recipients: ['admin@alphamail.my'],
          receivedDateTime: new Date(now.getTime() - 18000000).toISOString(),
          sentDateTime: new Date(now.getTime() - 18000000).toISOString(),
          readStatus: false,
          size: 1792,
        },
        {
          id: 6,
          subject: '신입 인수인계',
          sender: 'onboarding@company.com',
          recipients: ['admin@alphamail.my'],
          receivedDateTime: new Date(now.getTime() - 21600000).toISOString(),
          sentDateTime: new Date(now.getTime() - 21600000).toISOString(),
          readStatus: false,
          size: 2304,
        },
        {
          id: 7,
          subject: '서버 점검 공지',
          sender: 'it@company.com',
          recipients: ['admin@alphamail.my'],
          receivedDateTime: new Date(now.getTime() - 25200000).toISOString(),
          sentDateTime: new Date(now.getTime() - 25200000).toISOString(),
          readStatus: false,
          size: 896,
        },
        {
          id: 8,
          subject: '이벤트 초대장',
          sender: 'events@company.com',
          recipients: ['admin@alphamail.my'],
          receivedDateTime: new Date(now.getTime() - 28800000).toISOString(),
          sentDateTime: new Date(now.getTime() - 28800000).toISOString(),
          readStatus: false,
          size: 2176,
        },
        {
          id: 9,
          subject: '인사 발령 안내',
          sender: 'hr@company.com',
          recipients: ['admin@alphamail.my'],
          receivedDateTime: new Date(now.getTime() - 32400000).toISOString(),
          sentDateTime: new Date(now.getTime() - 32400000).toISOString(),
          readStatus: true,
          size: 1024,
        },
        {
          id: 10,
          subject: '11월 경비 승인 대기',
          sender: 'finance@company.com',
          recipients: ['admin@alphamail.my'],
          receivedDateTime: new Date(now.getTime() - 36000000).toISOString(),
          sentDateTime: new Date(now.getTime() - 36000000).toISOString(),
          readStatus: true,
          size: 5120,
        },
        {
          id: 6,
          subject: '품질 개선 사항',
          sender: 'qa@company.com',
          recipients: ['admin@alphamail.my'],
          receivedDateTime: new Date(now.getTime() - 21600000).toISOString(),
          sentDateTime: new Date(now.getTime() - 21600000).toISOString(),
          readStatus: false,
          size: 2560,
        },
        {
          id: 7,
          subject: '마케팅 전략 회의',
          sender: 'marketing@company.com',
          recipients: ['admin@alphamail.my'],
          receivedDateTime: new Date(now.getTime() - 25200000).toISOString(),
          sentDateTime: new Date(now.getTime() - 25200000).toISOString(),
          readStatus: true,
          size: 3456,
        },
        {
          id: 8,
          subject: '고객 피드백 공유',
          sender: 'customer@client.com',
          recipients: ['admin@alphamail.my'],
          receivedDateTime: new Date(now.getTime() - 28800000).toISOString(),
          sentDateTime: new Date(now.getTime() - 28800000).toISOString(),
          readStatus: false,
          size: 1792,
        },
        {
          id: 9,
          subject: '프로젝트 완료 보고서',
          sender: 'project@company.com',
          recipients: ['admin@alphamail.my'],
          receivedDateTime: new Date(now.getTime() - 32400000).toISOString(),
          sentDateTime: new Date(now.getTime() - 32400000).toISOString(),
          readStatus: true,
          size: 4608,
        },
        {
          id: 10,
          subject: '신입 인수인계',
          sender: 'onboarding@company.com',
          recipients: ['admin@alphamail.my'],
          receivedDateTime: new Date(now.getTime() - 36000000).toISOString(),
          sentDateTime: new Date(now.getTime() - 36000000).toISOString(),
          readStatus: false,
          size: 2304,
        },
        {
          id: 11,
          subject: '분기 실적 보고',
          sender: 'finance@company.com',
          recipients: ['admin@alphamail.my'],
          receivedDateTime: new Date(now.getTime() - 39600000).toISOString(),
          sentDateTime: new Date(now.getTime() - 39600000).toISOString(),
          readStatus: true,
          size: 5760,
        },
        {
          id: 12,
          subject: '서버 점검 공지',
          sender: 'it@company.com',
          recipients: ['admin@alphamail.my'],
          receivedDateTime: new Date(now.getTime() - 43200000).toISOString(),
          sentDateTime: new Date(now.getTime() - 43200000).toISOString(),
          readStatus: false,
          size: 896,
        },
        {
          id: 13,
          subject: '계약서 검토 요청',
          sender: 'legal@company.com',
          recipients: ['admin@alphamail.my'],
          receivedDateTime: new Date(now.getTime() - 46800000).toISOString(),
          sentDateTime: new Date(now.getTime() - 46800000).toISOString(),
          readStatus: true,
          size: 3840,
        },
        {
          id: 14,
          subject: '이벤트 초대장',
          sender: 'events@company.com',
          recipients: ['admin@alphamail.my'],
          receivedDateTime: new Date(now.getTime() - 50400000).toISOString(),
          sentDateTime: new Date(now.getTime() - 50400000).toISOString(),
          readStatus: false,
          size: 2176,
        },
        {
          id: 15,
          subject: '월간 뉴스레터',
          sender: 'newsletter@company.com',
          recipients: ['admin@alphamail.my'],
          receivedDateTime: new Date(now.getTime() - 54000000).toISOString(),
          sentDateTime: new Date(now.getTime() - 54000000).toISOString(),
          readStatus: true,
          size: 6144,
        },
      ],
      totalCount: 15,
      readCount: 7,
      pageCount: 1,
      currentPage: 0,
    };
  };
  
  export const createMockAssistants = () => {
    const now = new Date();
    return {
      contents: [
        {
          id: 1,
          type: 'SCHEDULE',
          title: '회의실 예약',
          userId: 1,
          emailId: 1,
          emailTime: new Date(now.getTime() - 3600000).toISOString(),
        },
        {
          id: 2,
          type: 'PURCHASE_ORDER',
          title: '발주서 - 용품 구매',
          userId: 1,
          emailId: 2,
          emailTime: new Date(now.getTime() - 7200000).toISOString(),
        },
        {
          id: 3,
          type: 'QUOTE',
          title: '견적서 - 프린터 임차료',
          userId: 1,
          emailId: 3,
          emailTime: new Date(now.getTime() - 10800000).toISOString(),
        },
        {
          id: 4,
          type: 'CLIENT',
          title: '거래처 등록 - ABC 회사',
          userId: 1,
          emailId: 4,
          emailTime: new Date(now.getTime() - 14400000).toISOString(),
        },
        {
          id: 5,
          type: 'PURCHASE_ORDER',
          title: '발주서 - 서버 장비',
          userId: 1,
          emailId: 5,
          emailTime: new Date(now.getTime() - 18000000).toISOString(),
        },
      ],
      totalCount: 5,
      pageCount: 1,
      currentPage: 0,
    };
  };
  
  export const createMockFolders = () => {
    return [
      {
        id: 1,
        userId: 1,
        folderName: 'INBOX',
        totalCount: 15,
        unreadCount: 3,
        createdAt: new Date().toISOString(),
      },
      {
        id: 2,
        userId: 1,
        folderName: 'SENT',
        totalCount: 8,
        unreadCount: 0,
        createdAt: new Date().toISOString(),
      },
      {
        id: 3,
        userId: 1,
        folderName: 'TRASH',
        totalCount: 5,
        unreadCount: 0,
        createdAt: new Date().toISOString(),
      },
    ];
  };
  
  export const createMockUser = () => {
    return {
      id: 1,
      companyId: 1,
      companyName: 'Alpha Company',
      groupId: 1,
      groupName: 'IT Team',
      position: 'Admin',
      name: 'Admin User',
      email: 'admin@alphamail.my',
      phoneNum: '010-1234-5678',
      image: '',
    };
  };