spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
# AWS SES 설정
aws:
  region: ap-northeast-2  # 선택한 AWS 리전
  ses:
    access-key: ${YOUR_ACCESS_KEY}
    secret-key: ${YOUR_SECRET_KEY}
    domain: alphamail.my  # 도메인만 설정
    system-sender: "AlphaMail System <noreply@alphamail.my>"  # 시스템용 이메일
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}

decorator:
  datasource:
    p6spy:
      enable-logging: true



jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: 3600  # 1시간
  # refresh-token-validity-in-seconds: 604800  # 7일 (향후 사용)